# Generated by Django 6.0.1 on 2026-02-18 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_category_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='categoryId',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
